### ISSUE TITLE
Get One Merchant

### ISSUE THREAD

**Issue by jphill19** [bwillett2003/little_shop#5]
Create:

- Route
- Controller method
- Test

**Comment by James-Cochran** [comment]
. Fetch all Items/Merchants
These “index” endpoints for items and merchants should:

render a JSON representation of all records of the requested resource
always return an array of data, even if one or zero resources are found
NOT include dependent data of the resource (e.g., if you’re fetching merchants, do not send any data about merchant’s items or invoices)
follow this pattern: GET /api/v1/<resource>
